#!/bin/bash

#############SETUP VARIABLES###############################################################################################

#IPTABLES
IPT=/sbin/iptables
#TC
TC=/sbin/tc
#LOCAL
#LOCAL_DL=100Mbit
#LOCAL_Ceil=100Mbit
#LOCAL_Prio=7
DL1=4500
UL1=900
Gst1=400
#Download
DL=$[DL1]Kbit
DL_Ceil=$[DL1]Kbit
DL_Prio=2
#Upload
UL=$[UL1]Kbit
UL_Ceil=$[UL1]Kbit
UL_Prio=0
#FQ_CODEL
quantum=300
#User Speed
Usr_DL=$[DL1/6]Kbit
Usr_DL_Ceil=$[DL1/4]Kbit
#Guest Speed
#Gst_DL=$[DL/5]Kbit
#Gst_DL_Ceil=$[DL_Ceil/5]Kbit
Gst_DL=$[Gst1]Kbit
Gst_DL_Ceil=$[Gst1]Kbit
Gst_DL_Prio=7
#############SETUP VARIABLES###############################################################################################

start() {
#############SETUP BASE CONNECTION#########################################################################################
$TC qdisc add dev eth0 root handle 1: htb default 100
#############SETUP BASE CONNECTION#########################################################################################
#############SETUP CLASSES#################################################################################################
#LOCAL
#$TC class add dev eth0 parent 1: classid 1:300 htb rate $LOCAL_DL ceil $LOCAL_Ceil prio $LOCAL_Prio
#	$TC qdisc add dev eth0 parent 1:300 fq_codel quantum $quantum
#DOWNLOAD
$TC class add dev eth0 parent 1: classid 1:1 htb rate $DL ceil $DL_Ceil prio $DL_Prio
#UPLOAD
$TC class add dev eth0 parent 1: classid 1:100 htb rate $UL ceil $UL_Ceil prio $UL_Prio
	$TC qdisc add dev eth0 parent 1:100 fq_codel quantum $quantum
#GUEST
$TC class add dev eth0 parent 1: classid 1:200 htb rate $Gst_DL ceil $Gst_DL_Ceil prio $Gst_DL_Prio
	$TC qdisc add dev eth0 parent 1:200 fq_codel quantum $quantum
##############ISLAM##########################
	$TC class add dev eth0 parent 1:1 classid 1:2 htb rate $Usr_DL ceil $Usr_DL_Ceil prio $DL_Prio
		$TC qdisc add dev eth0 parent 1:2 fq_codel quantum $quantum
##############HAMDY##########################
	$TC class add dev eth0 parent 1:1 classid 1:3 htb rate $Usr_DL ceil $Usr_DL_Ceil prio $DL_Prio
		$TC qdisc add dev eth0 parent 1:3 fq_codel quantum $quantum
##############AHMED##########################
	$TC class add dev eth0 parent 1:1 classid 1:4 htb rate $Usr_DL ceil $Usr_DL_Ceil prio $DL_Prio
		$TC qdisc add dev eth0 parent 1:4 fq_codel quantum $quantum
##############MARAM##########################
	$TC class add dev eth0 parent 1:1 classid 1:5 htb rate $Usr_DL ceil $Usr_DL_Ceil prio $DL_Prio
		$TC qdisc add dev eth0 parent 1:5 fq_codel quantum $quantum
##############MAMA##########################
	$TC class add dev eth0 parent 1:1 classid 1:6 htb rate $Usr_DL ceil $Usr_DL_Ceil prio $DL_Prio
		$TC qdisc add dev eth0 parent 1:6 fq_codel quantum $quantum
##############BABA##########################
	$TC class add dev eth0 parent 1:1 classid 1:7 htb rate $Usr_DL ceil $Usr_DL_Ceil prio $DL_Prio
		$TC qdisc add dev eth0 parent 1:7 fq_codel quantum $quantum
##############OTHERS##########################
#############SETUP CLASSES#################################################################################################
#############SETUP ROUTING FILTERS#########################################################################################
##############UPLOAD#########################
##############TCP CONNECTION START###########
$IPT -t mangle -A PREROUTING -p icmp -j MARK --set-mark 1
$IPT -t mangle -A PREROUTING -p icmp -j RETURN
$IPT -t mangle -A FORWARD -p icmp -j MARK --set-mark 1
$IPT -t mangle -A FORWARD -p icmp -j RETURN
$IPT -t mangle -A PREROUTING -p tcp -m tcp --tcp-flags SYN,RST,ACK SYN -j MARK --set-mark 1
$IPT -t mangle -A PREROUTING -p tcp -m tcp --tcp-flags SYN,RST,ACK SYN -j RETURN
$IPT -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST,ACK SYN -j MARK --set-mark 1
$IPT -t mangle -A FORWARD -p tcp -m tcp --tcp-flags SYN,RST,ACK SYN -j RETURN
$TC filter add dev eth0 protocol ip parent 1: handle 1 fw flowid 1:100
##############ISLAM##########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.20-192.168.1.29 -j MARK --set-mark 2
$TC filter add dev eth0 protocol ip parent 1: handle 2 fw flowid 1:2
##############HAMDY##########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.30-192.168.1.39 -j MARK --set-mark 3
$TC filter add dev eth0 protocol ip parent 1: handle 3 fw flowid 1:3
##############AHMED##########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.40-192.168.1.49 -j MARK --set-mark 4
$TC filter add dev eth0 protocol ip parent 1: handle 4 fw flowid 1:4
##############MARAM##########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.50-192.168.1.69 -j MARK --set-mark 5
$TC filter add dev eth0 protocol ip parent 1: handle 5 fw flowid 1:5
##############MAMA###########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.60-192.168.1.69 -j MARK --set-mark 6
$TC filter add dev eth0 protocol ip parent 1: handle 6 fw flowid 1:6
##############BABA###########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.70-192.168.1.79 -j MARK --set-mark 7
$TC filter add dev eth0 protocol ip parent 1: handle 7 fw flowid 1:7
##############SERVERS########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.2-192.168.1.19 -j MARK --set-mark 8
$IPT -t mangle -A FORWARD -i eth0 -m iprange --src-range 192.168.1.2-192.168.1.19 -j MARK --set-mark 8
$TC filter add dev eth0 protocol ip parent 1: handle 8 fw flowid 1:1
##############GUESTS#########################
$IPT -t mangle -A FORWARD -i eth0 -m iprange --dst-range 192.168.1.80-192.168.1.254 -j MARK --set-mark 9
$IPT -t mangle -A FORWARD -i eth0 -m iprange --src-range 192.168.1.80-192.168.1.254 -j MARK --set-mark 9
$TC filter add dev eth0 protocol ip parent 1: handle 9 fw flowid 1:200
##############LOCAL##########################
#$IPT -t mangle -A PREROUTING -i eth0 -s 192.168.1.0/24 d- 192.168.1.0/24 -j MARK --set-mark 10
#$TC filter add dev eth0 protocol ip parent 1: handle 10 fw flowid 1:300
#############SETUP ROUTING FILTERS#########################################################################################
}

stop() {
    $IPT -t mangle -F
	$TC qdisc del dev eth0 root
}

case "$1" in
    'start')
            start
            ;;
    'stop')
            stop
            ;;
    'restart')
            stop ; echo "Sleeping..."; sleep 2 ;
            start
            ;;
    *)
            echo
            echo "Usage: $0 { start | stop | restart }"
            echo
            exit 1
            ;;
esac

exit 0